server:
  port: 8888
spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:default}
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/diego97f/spring-cloud-config-repo.git
          default-label: master
          search-paths: '{application}'
          timeout: 5
          clone-on-start: true
          force-pull: true
        health:
          repositories:
            check:
              name: health-check
              label: master
  security:
    user:
      name: ${CONFIG_SERVER_USERNAME:configadmin}
      password: ${CONFIG_SERVER_PASSWORD:secretpassword}
management:
  endpoints:
    web:
      exposure:
        include: health,info,env,metrics
  endpoint:
    health:
      show-details: always